### ISSUE TITLE
「常见问题」遗漏配置中的页面标识相关字段，导致评论无法刷新

### ISSUE THREAD

**Issue by dolyw** [dongyuanxin/vuepress-plugin-comment#4]
如题，VuePress页面切换不会重新加载Valine的评论的，导致评论一直是第一个页面的

**Comment by dongyuanxin** [comment]
@dolyw 是否是最新版本？提供一下用法例子或者仓库地址。

**Comment by dolyw** [comment]
https://github.com/wliduo/Note
https://note.dolyw.com

**Comment by dolyw** [comment]
都是安装的最新版本

**Comment by dolyw** [comment]
我看其他人是自己写了一个自定义组件进行watch监听路由是否变化去刷新评论的

**Comment by dolyw** [comment]
![image](https://user-images.githubusercontent.com/36805568/69120910-cce39480-0ad5-11ea-8f6b-1481185f2e26.png)
https://segmentfault.com/a/1190000017953711?utm_source=tag-newest#articleHeader10

**Comment by dongyuanxin** [comment]
> @dolyw  
> 都是安装的最新版本

A：问题已经排查，插件没有问题。

> 我看其他人是自己写了一个自定义组件进行watch监听路由是否变化去刷新评论的

A: 插件自带路由监听，并且针对渲染、防抖和加载做了各种优化

> VuePress页面切换不会重新加载Valine的评论的，导致评论一直是第一个页面的

A: 问题出现出现在 [`/doc/.vuepress/config.js`](https://github.com/wliduo/Note/blob/f21f451c3ec9ab718f5589316dd6250dfc85b161/doc/.vuepress/config.js#L30-L40)。**插件的配置没有指明`path`字段**。请参考[vuepress-plugin-comment#vue-in-valine](https://github.com/dongyuanxin/vuepress-plugin-comment/blob/master/README.md#use-in-valine)

**Comment by dolyw** [comment]
![image](https://user-images.githubusercontent.com/36805568/69123221-c6581b80-0adb-11ea-9901-a32639536716.png)
这样还是不行，直接获取路径，我不想每个文章都去加参数

**Comment by dongyuanxin** [comment]
> @dolyw 
> 这样还是不行，直接获取路径，我不想每个文章都去加参数

换成：`'<%- frontmatter.to.path %>'` 即可。在vuepress中，window上的路由对象拿到的信息不一定是正确的，插件自动给`frontmatter`变量注册了`from`和`to`对象，请在其上获取路由信息。

**Comment by dolyw** [comment]
感谢你的耐心解答，我改了下，可以了，还有个VuePress的插件问题
![image](https://user-images.githubusercontent.com/36805568/69130698-ec85b780-0aeb-11ea-9379-d9518a9987ea.png)
不知道为什么这两个引入报错，我已经安装了

**Comment by dolyw** [comment]
warning An error was encounted in plugin "@vuepress/active-header-links"
warning An error was encounted in plugin "@vuepress/back-to-top"
warning An error was encounted in plugin "@vuepress/active-header-links"
![image](https://user-images.githubusercontent.com/36805568/69130873-438b8c80-0aec-11ea-9a7b-60514565dbbd.png)

**Comment by dolyw** [comment]
解决了，谢谢

**Comment by dongyuanxin** [comment]
> @dolyw 
> 解决了，谢谢

Reopen for other people

**Comment by yinxin630** [comment]
我有 `base` 配置, 设置成 `<%- frontmatter.to.path %>` 不行, 不包含 base 路径, 这种情况该怎么办

**Comment by yinxin630** [comment]
> 我有 `base` 配置, 设置成 `<%- frontmatter.to.path %>` 不行, 不包含 base 路径, 这种情况该怎么办

我找到一个解决办法, 配置成 `<%- frontmatter.to.path ? "/base" + frontmatter.to.path : window.location.pathname %>` 即可

**Comment by kaizige10** [comment]
> > @dolyw
> > 这样还是不行，直接获取路径，我不想每个文章都去加参数
> 
> 换成：`'<%- frontmatter.to.path %>'` 即可。在vuepress中，window上的路由对象拿到的信息不一定是正确的，插件自动给`frontmatter`变量注册了`from`和`to`对象，请在其上获取路由信息。

按照这个方法确实解决了，赞~

**Comment by yiliang114** [comment]
如果想统计每一个页面的请求量，path 设置了 `<%- frontmatter.to.path %>` 这个会让除了首次访问以外，切换路由之后的访问量都为 0

**Comment by ajunxu** [comment]
> > @dolyw
> > 这样还是不行，直接获取路径，我不想每个文章都去加参数
> 
> 换成：`'<%- frontmatter.to.path %>'` 即可。在vuepress中，window上的路由对象拿到的信息不一定是正确的，插件自动给`frontmatter`变量注册了`from`和`to`对象，请在其上获取路由信息。

配置成'<%- frontmatter.to.path %>' 这样，但是页面刷新，评论就消失了，要切换到下一页，再切换回上一页，评论才出现，所以path要怎么设置

**Comment by swhmonster** [comment]
禁用评论，无效果，配置comments: false
