### ISSUE TITLE
add magin & padding to comment

### ISSUE THREAD

**Issue by franklinqin0** [dongyuanxin/vuepress-plugin-comment#6]
When I used the "gitalk" option, there comment area is at full width. I wonder if you could add some padding s.t. the comment area is more visually appealing? The suggested parameters for id `vuepress-plugin-comment` is:

```styl
margin: 0 auto;
padding: 2rem 2.5rem;
```

Thanks!

**Comment by franklinqin0** [comment]
I opened a PL at: [https://github.com/dongyuanxin/vuepress-plugin-comment/pull/7]()

**Comment by 40huo** [comment]
可以直接加在这里 https://vuepress.vuejs.org/zh/config/#index-styl

**Comment by AJ-X** [comment]
@franklinqin0 Have you solved it?
there comment area is at full width this problem
